# Generated by Django 5.1 on 2024-09-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productversion"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductVersion",
            new_name="Version",
        ),
    ]
